services:
  commandes:
    container_name: commandes
    image: node:lts
    env_file: commandes/.env
    working_dir: /usr/src/app
    volumes:
      - ./commandes/api:/usr/src/app
    ports:
      - 3333:3000
    #command: bash -c "npm i && npm start"
    command: npm run watch
    depends_on:
      - commandes_db
    links:
      - commandes_db
    networks:
      - lbs

  suivi_commandes:
    container_name: suivi_commandes
    image: node:lts
    env_file: suivi_commandes/.env
    working_dir: /usr/src/app
    volumes:
      - ./suivi_commandes/api:/usr/src/app
    ports:
      - 3334:3000
    #command: bash -c "npm i && npm start"
    command: npm run watch
    depends_on:
      - commandes_db
    links:
      - commandes_db
    networks:
      - lbs

  lbs_adminer:
    container_name: lbs_adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - commandes_db
    networks:
      - lbs
      
  commandes_db:
    container_name: commandes_db
    image: mariadb:latest
    env_file: commandes_db/.env
    volumes:
      - ./commandes_db/db:/var/lib/mysql
      - ./commandes_db/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./commandes_db/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - lbs

networks:
  lbs:
    driver: bridge